# Use the official PyTorch base image
FROM pytorch/pytorch:latest

# Set working directory
WORKDIR /app

# Copy the requirements and install dependencies
COPY requirements.txt /app/requirements.txt
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy the training script
COPY train.py /app/train.py

# Execute the training script when the container starts
CMD ["python", "train.py"]
